## Install yfinance

In [2]:
%pip install yfinance

Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple/
Requirement already satisfied: yfinance in /Users/tiny/Apps/anaconda3/envs/mytalib/lib/python3.10/site-packages (0.2.37)
Requirement already satisfied: pandas>=1.3.0 in /Users/tiny/Apps/anaconda3/envs/mytalib/lib/python3.10/site-packages (from yfinance) (2.2.1)
Requirement already satisfied: numpy>=1.16.5 in /Users/tiny/Apps/anaconda3/envs/mytalib/lib/python3.10/site-packages (from yfinance) (1.26.4)
Requirement already satisfied: requests>=2.31 in /Users/tiny/Apps/anaconda3/envs/mytalib/lib/python3.10/site-packages (from yfinance) (2.31.0)
Requirement already satisfied: multitasking>=0.0.7 in /Users/tiny/Apps/anaconda3/envs/mytalib/lib/python3.10/site-packages (from yfinance) (0.0.11)
Requirement already satisfied: lxml>=4.9.1 in /Users/tiny/Apps/anaconda3/envs/mytalib/lib/python3.10/site-packages (from yfinance) (5.1.0)
Requirement already satisfied: appdirs>=1.4.4 in /Users/tiny/Apps/anaconda3/envs/mytalib/lib/python3.10/site-packages (from yfinance) (1.4.4)
Requirement already satisfied: pytz>=2022.5 in /Users/tiny/Apps/anaconda3/envs/mytalib/lib/python3.10/site-packages (from yfinance) (2024.1)
Requirement already satisfied: frozendict>=2.3.4 in /Users/tiny/Apps/anaconda3/envs/mytalib/lib/python3.10/site-packages (from yfinance) (2.4.0)
Requirement already satisfied: peewee>=3.16.2 in /Users/tiny/Apps/anaconda3/envs/mytalib/lib/python3.10/site-packages (from yfinance) (3.17.1)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /Users/tiny/Apps/anaconda3/envs/mytalib/lib/python3.10/site-packages (from yfinance) (4.12.3)
Requirement already satisfied: html5lib>=1.1 in /Users/tiny/Apps/anaconda3/envs/mytalib/lib/python3.10/site-packages (from yfinance) (1.1)
Requirement already satisfied: soupsieve>1.2 in /Users/tiny/Apps/anaconda3/envs/mytalib/lib/python3.10/site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.5)
Requirement already satisfied: six>=1.9 in /Users/tiny/Apps/anaconda3/envs/mytalib/lib/python3.10/site-packages (from html5lib>=1.1->yfinance) (1.16.0)
Requirement already satisfied: webencodings in /Users/tiny/Apps/anaconda3/envs/mytalib/lib/python3.10/site-packages (from html5lib>=1.1->yfinance) (0.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/tiny/Apps/anaconda3/envs/mytalib/lib/python3.10/site-packages (from pandas>=1.3.0->yfinance) (2.9.0)
Requirement already satisfied: tzdata>=2022.7 in /Users/tiny/Apps/anaconda3/envs/mytalib/lib/python3.10/site-packages (from pandas>=1.3.0->yfinance) (2024.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/tiny/Apps/anaconda3/envs/mytalib/lib/python3.10/site-packages (from requests>=2.31->yfinance) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /Users/tiny/Apps/anaconda3/envs/mytalib/lib/python3.10/site-packages (from requests>=2.31->yfinance) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/tiny/Apps/anaconda3/envs/mytalib/lib/python3.10/site-packages (from requests>=2.31->yfinance) (2.2.1)
Requirement already satisfied: certifi>=2017.4.17 in /Users/tiny/Apps/anaconda3/envs/mytalib/lib/python3.10/site-packages (from requests>=2.31->yfinance) (2024.2.2)
Note: you may need to restart the kernel to use updated packages.

## Import yfinance and Pandas

In [1]:
import pandas as pd
import yfinance as yf

In [2]:
dir(yf)

['Ticker',
 'Tickers',
 '__all__',
 '__author__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 'base',
 'download',
 'multi',
 'pdr_override',
 'set_tz_cache_location',
 'shared',
 'ticker',
 'tickers',
 'utils',
 'version']

## How to Download Historical Price Data Using yfinance

We can download data for one ticker using the Ticker object and multiple tickers using the download method.

### Download One Ticker Using yfinance

First, we need to create a ticker object and then use that object to get our data. Creating a ticker object is straightforward:

In [5]:
obj = yf.Ticker('goog')
obj

yfinance.Ticker object <GOOG>

In [6]:
dir(obj)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_analysis',
 '_data',
 '_download_options',
 '_earnings',
 '_earnings_dates',
 '_expirations',
 '_fast_info',
 '_fetch_ticker_tz',
 '_financials',
 '_fundamentals',
 '_get_ticker_tz',
 '_holders',
 '_isin',
 '_lazy_load_price_history',
 '_news',
 '_options2df',
 '_price_history',
 '_quote',
 '_shares',
 '_tz',
 '_underlying',
 'actions',
 'analyst_price_target',
 'balance_sheet',
 'balancesheet',
 'basic_info',
 'calendar',
 'capital_gains',
 'cash_flow',
 'cashflow',
 'dividends',
 'earnings',
 'earnings_dates',
 'earnings_forecasts',
 'earnings_trend',
 'fast_info',
 'financials',
 'get_actions',
 'get_analyst_price_target',
 'get_balance_sheet',
 'get_balancesheet',
 'get_calendar',
 'get_capital_gains',
 'get_cash_flow',
 'get_cashflow',
 'get_dividends',
 'get_earnings',
 'get_earnings_dates',
 'get_earnings_forecast',
 'get_earnings_trend',
 'get_fast_info',
 'get_financials',
 'get_history_metadata',
 'get_income_stmt',
 'get_incomestmt',
 'get_info',
 'get_insider_purchases',
 'get_insider_roster_holders',
 'get_insider_transactions',
 'get_institutional_holders',
 'get_isin',
 'get_major_holders',
 'get_mutualfund_holders',
 'get_news',
 'get_recommendations',
 'get_recommendations_summary',
 'get_rev_forecast',
 'get_shares',
 'get_shares_full',
 'get_splits',
 'get_sustainability',
 'get_trend_details',
 'get_upgrades_downgrades',
 'history',
 'history_metadata',
 'income_stmt',
 'incomestmt',
 'info',
 'insider_purchases',
 'insider_roster_holders',
 'insider_transactions',
 'institutional_holders',
 'isin',
 'major_holders',
 'mutualfund_holders',
 'news',
 'option_chain',
 'options',
 'proxy',
 'quarterly_balance_sheet',
 'quarterly_balancesheet',
 'quarterly_cash_flow',
 'quarterly_cashflow',
 'quarterly_earnings',
 'quarterly_financials',
 'quarterly_income_stmt',
 'quarterly_incomestmt',
 'recommendations',
 'recommendations_summary',
 'revenue_forecasts',
 'session',
 'shares',
 'splits',
 'sustainability',
 'ticker',
 'trend_details',
 'upgrades_downgrades']

In [7]:
goog = yf.Ticker('goog')
data = goog.history()
data.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2024-02-13 00:00:00-05:00,146.070007,148.039993,145.110001,146.369995,18138500,0.0,0.0
2024-02-14 00:00:00-05:00,147.369995,147.830002,145.554993,147.139999,16651800,0.0,0.0
2024-02-15 00:00:00-05:00,144.460007,144.759995,141.880005,143.940002,26724300,0.0,0.0
2024-02-16 00:00:00-05:00,144.210007,144.479996,141.520004,141.759995,21849700,0.0,0.0
2024-02-20 00:00:00-05:00,140.940002,143.328995,140.800003,142.199997,18625600,0.0,0.0

In [9]:
data = goog.history(interval='1m', start='2024-03-03', end='2024-03-10')
data.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Datetime,,,,,,,
2024-03-04 09:30:00-05:00,136.250000,136.580002,135.600006,135.820007,1277554,0.0,0.0
2024-03-04 09:31:00-05:00,135.809998,135.869995,134.720001,135.244995,468446,0.0,0.0
2024-03-04 09:32:00-05:00,134.759995,134.787094,134.735001,134.779999,899298,0.0,0.0
2024-03-04 09:33:00-05:00,135.000000,135.008896,134.820007,134.860001,372565,0.0,0.0
2024-03-04 09:34:00-05:00,134.859894,134.899994,134.410004,134.509903,309471,0.0,0.0

### Download Multiple Tickers Using yfinance

In [10]:
data = yf.download(['GOOG','META'], period='1mo')
data.head()

[*********************100%%**********************]  2 of 2 completed

Price        Adj Close                   Close                    High  \
Ticker            GOOG        META        GOOG        META        GOOG
Date
2024-02-13  146.369995  459.632324  146.369995  460.119995  148.039993
2024-02-14  147.139999  472.778381  147.139999  473.279999  147.830002
2024-02-15  143.940002  483.516968  143.940002  484.029999  144.759995
2024-02-16  141.759995  472.818329  141.759995  473.320007  144.479996
2024-02-20  142.199997  471.250000  142.199997  471.750000  143.328995

Price                          Low                    Open              \
Ticker            META        GOOG        META        GOOG        META
Date
2024-02-13  467.890015  145.110001  455.089996  146.070007  456.869995
2024-02-14  474.109985  145.554993  466.089996  147.369995  467.929993
2024-02-15  488.619995  141.880005  472.220001  144.460007  475.279999
2024-02-16  478.959991  141.520004  469.209991  144.210007  478.109985
2024-02-20  476.179993  140.800003  466.559998  140.940002  469.720001

Price         Volume
Ticker          GOOG      META
Date
2024-02-13  18138500  20916600
2024-02-14  16651800  16858400
2024-02-15  26724300  24212300
2024-02-16  21849700  23306500
2024-02-20  18625600  18015500

In [11]:
data = yf.download(['GOOG','META'], start='2021-12-10', end='2021-12-30', group_by='ticker')
data.head()

[*********************100%%**********************]  2 of 2 completed

Ticker            GOOG                                                  \
Price             Open        High         Low       Close   Adj Close
Date
2021-12-10  149.100006  149.399994  147.357498  148.675003  148.675003
2021-12-13  148.444000  148.562500  146.360001  146.704498  146.704498
2021-12-14  144.770004  145.442001  142.242493  144.970505  144.970505
2021-12-15  144.365997  147.517242  142.705505  147.368500  147.368500
2021-12-16  148.076996  148.551498  144.092499  144.838501  144.838501

Ticker                      META                                      \
Price         Volume        Open        High         Low       Close
Date
2021-12-10  21634000  332.559998  335.029999  326.369995  329.750000
2021-12-13  24104000  330.950012  341.089996  329.589996  334.489990
2021-12-14  24778000  328.049988  335.700012  327.649994  333.739990
2021-12-15  27280000  332.489990  342.109985  323.980011  341.660004
2021-12-16  27400000  338.980011  344.459991  333.739990  334.899994

Ticker
Price        Adj Close    Volume
Date
2021-12-10  329.400513  14528000
2021-12-13  334.135468  22948700
2021-12-14  333.386261  20461000
2021-12-15  341.297882  24681300
2021-12-16  334.545044  22635000

## How to Download Fundamental Data Using yfinance

We can loop through multiple tickers objects to download fundamental data for various tickers.

In [14]:
dhr = yf.Ticker('DHR')
info = dhr.info
info.keys()

dict_keys(['address1', 'address2', 'city', 'state', 'zip', 'country', 'phone', 'fax', 'website', 'industry', 'industryKey', 'industryDisp', 'sector', 'sectorKey', 'sectorDisp', 'longBusinessSummary', 'fullTimeEmployees', 'companyOfficers', 'auditRisk', 'boardRisk', 'compensationRisk', 'shareHolderRightsRisk', 'overallRisk', 'governanceEpochDate', 'compensationAsOfEpochDate', 'maxAge', 'priceHint', 'previousClose', 'open', 'dayLow', 'dayHigh', 'regularMarketPreviousClose', 'regularMarketOpen', 'regularMarketDayLow', 'regularMarketDayHigh', 'dividendRate', 'dividendYield', 'exDividendDate', 'payoutRatio', 'fiveYearAvgDividendYield', 'beta', 'trailingPE', 'forwardPE', 'volume', 'regularMarketVolume', 'averageVolume', 'averageVolume10days', 'averageDailyVolume10Day', 'bid', 'bidSize', 'askSize', 'marketCap', 'fiftyTwoWeekLow', 'fiftyTwoWeekHigh', 'priceToSalesTrailing12Months', 'fiftyDayAverage', 'twoHundredDayAverage', 'trailingAnnualDividendRate', 'trailingAnnualDividendYield', 'currency', 'enterpriseValue', 'profitMargins', 'floatShares', 'sharesOutstanding', 'sharesShort', 'sharesShortPriorMonth', 'sharesShortPreviousMonthDate', 'dateShortInterest', 'sharesPercentSharesOut', 'heldPercentInsiders', 'heldPercentInstitutions', 'shortRatio', 'shortPercentOfFloat', 'impliedSharesOutstanding', 'bookValue', 'priceToBook', 'lastFiscalYearEnd', 'nextFiscalYearEnd', 'mostRecentQuarter', 'earningsQuarterlyGrowth', 'netIncomeToCommon', 'trailingEps', 'forwardEps', 'pegRatio', 'lastSplitFactor', 'lastSplitDate', 'enterpriseToRevenue', 'enterpriseToEbitda', '52WeekChange', 'SandP52WeekChange', 'lastDividendValue', 'lastDividendDate', 'exchange', 'quoteType', 'symbol', 'underlyingSymbol', 'shortName', 'longName', 'firstTradeDateEpochUtc', 'timeZoneFullName', 'timeZoneShortName', 'uuid', 'messageBoardId', 'gmtOffSetMilliseconds', 'currentPrice', 'targetHighPrice', 'targetLowPrice', 'targetMeanPrice', 'targetMedianPrice', 'recommendationMean', 'recommendationKey', 'numberOfAnalystOpinions', 'totalCash', 'totalCashPerShare', 'ebitda', 'totalDebt', 'quickRatio', 'currentRatio', 'totalRevenue', 'debtToEquity', 'revenuePerShare', 'returnOnAssets', 'returnOnEquity', 'freeCashflow', 'operatingCashflow', 'earningsGrowth', 'revenueGrowth', 'grossMargins', 'ebitdaMargins', 'operatingMargins', 'financialCurrency', 'trailingPegRatio'])

In [15]:
info['sector']

'Healthcare'

In [20]:
#dhr.get_earnings_dates()
dhr.earnings_dates

                           EPS Estimate  Reported EPS  Surprise(%)
Earnings Date
2025-01-28 06:00:00-05:00           NaN           NaN          NaN
2024-10-22 06:00:00-04:00           NaN           NaN          NaN
2024-07-23 08:00:00-04:00           NaN           NaN          NaN
2024-04-23 08:00:00-04:00          1.71           NaN          NaN
2024-01-30 06:00:00-05:00          1.91          2.09       0.0961
2023-10-24 06:00:00-04:00          1.87          2.02       0.0828
2023-07-25 06:00:00-04:00          2.01          2.05       0.0219
2023-04-25 06:00:00-04:00          2.25          2.36       0.0489
2023-01-24 06:00:00-05:00          2.54          2.87       0.1278
2022-10-20 06:00:00-04:00          2.26          2.56       0.1325
2022-07-21 06:00:00-04:00          2.35          2.76       0.1747
2022-04-21 06:00:00-04:00          2.66          2.76       0.0367

In [21]:
dhr.get_financials()

,2023-12-31,2022-12-31,2021-12-31,2020-12-31
TaxEffectOfUnusualItems,-42217000.0,-30894000.0,48900000.0,84483000.0
TaxRateForCalcs,0.163,0.114,0.163,0.189
NormalizedEBITDA,7755000000.0,9753000000.0,8504000000.0,6098000000.0
TotalUnusualItems,-259000000.0,-271000000.0,300000000.0,447000000.0
TotalUnusualItemsExcludingGoodwill,-259000000.0,-271000000.0,300000000.0,447000000.0
NetIncomeFromContinuingOperationNetMinorityInterest,4221000000.0,6328000000.0,5447000000.0,3646000000.0
ReconciledDepreciation,2166000000.0,2132000000.0,2062000000.0,1775000000.0
ReconciledCostOfRevenue,9856000000.0,10455000000.0,9563000000.0,9809000000.0
EBITDA,7496000000.0,9482000000.0,8804000000.0,6545000000.0
EBIT,5330000000.0,7350000000.0,6742000000.0,4770000000.0
NetInterestIncome,17000000.0,-163000000.0,-220000000.0,-204000000.0
InterestExpense,286000000.0,204000000.0,231000000.0,275000000.0
InterestIncome,303000000.0,41000000.0,11000000.0,71000000.0
NormalizedIncome,4437783000.0,6568106000.0,5195900000.0,3283483000.0
NetIncomeFromContinuingAndDiscontinuedOperation,4764000000.0,7209000000.0,6433000000.0,3646000000.0
TotalExpenses,18611000000.0,19107000000.0,18415000000.0,18053000000.0
TotalOperatingIncomeAsReported,5202000000.0,7536000000.0,6377000000.0,4231000000.0
DilutedAverageShares,743100000.0,737100000.0,736800000.0,718700000.0
BasicAverageShares,736500000.0,725100000.0,714600000.0,706200000.0
DilutedEPS,6.38,9.66,8.61,4.89
BasicEPS,6.44,9.8,8.77,4.97
DilutedNIAvailtoComStockholders,4743000000.0,7103000000.0,6269000000.0,3510000000.0
AverageDilutionEarnings,NaN,NaN,NaN,1000000.0
NetIncomeCommonStockholders,4743000000.0,7103000000.0,6269000000.0,3510000000.0
PreferredStockDividends,21000000.0,106000000.0,164000000.0,136000000.0
NetIncome,4764000000.0,7209000000.0,6433000000.0,3646000000.0
NetIncomeIncludingNoncontrollingInterests,4764000000.0,7209000000.0,6433000000.0,3646000000.0
NetIncomeDiscontinuousOperations,543000000.0,881000000.0,986000000.0,0.0
NetIncomeContinuousOperations,4221000000.0,6328000000.0,5447000000.0,3646000000.0
TaxProvision,823000000.0,818000000.0,1064000000.0,849000000.0
PretaxIncome,5044000000.0,7146000000.0,6511000000.0,4495000000.0
OtherIncomeExpense,-252000000.0,-227000000.0,344000000.0,468000000.0
OtherNonOperatingIncomeExpenses,7000000.0,44000000.0,44000000.0,21000000.0
SpecialIncomeCharges,-108000000.0,-91000000.0,-101000000.0,429000000.0
GainOnSaleOfBusiness,0.0,0.0,5000000.0,455000000.0
OtherSpecialCharges,NaN,NaN,96000000.0,26000000.0
WriteOff,108000000.0,91000000.0,10000000.0,NaN
GainOnSaleOfSecurity,-151000000.0,-180000000.0,401000000.0,18000000.0
NetNonOperatingInterestIncomeExpense,17000000.0,-163000000.0,-220000000.0,-204000000.0
InterestExpenseNonOperating,286000000.0,204000000.0,231000000.0,275000000.0
InterestIncomeNonOperating,303000000.0,41000000.0,11000000.0,71000000.0
OperatingIncome,5279000000.0,7536000000.0,6387000000.0,4231000000.0
OperatingExpense,8755000000.0,8652000000.0,8852000000.0,8244000000.0
OtherOperatingExpenses,NaN,NaN,547000000.0,NaN
ResearchAndDevelopment,1503000000.0,1528000000.0,1498000000.0,1348000000.0
SellingGeneralAndAdministration,7252000000.0,7124000000.0,6807000000.0,6896000000.0
GrossProfit,14034000000.0,16188000000.0,15239000000.0,12475000000.0
CostOfRevenue,9856000000.0,10455000000.0,9563000000.0,9809000000.0
TotalRevenue,23890000000.0,26643000000.0,24802000000.0,22284000000.0
OperatingRevenue,23890000000.0,26643000000.0,24802000000.0,22284000000.0

In [25]:
pnl = dhr.financials
bs = dhr.balancesheet
cf = dhr.cashflow
fs = pd.concat([pnl,bs,cf])
fs.to_csv('data/dhr_fs.csv')

In [26]:
fs.T

,Tax Effect Of Unusual Items,Tax Rate For Calcs,Normalized EBITDA,Total Unusual Items,Total Unusual Items Excluding Goodwill,Net Income From Continuing Operation Net Minority Interest,Reconciled Depreciation,Reconciled Cost Of Revenue,EBITDA,EBIT,...,Other Non Cash Items,Stock Based Compensation,Depreciation Amortization Depletion,Depreciation And Amortization,Amortization Cash Flow,Amortization Of Intangibles,Depreciation,Operating Gains Losses,Gain Loss On Sale Of Business,Net Income From Continuing Operations
2023-12-31,-42217000.0,0.163,7755000000.0,-259000000.0,-259000000.0,4221000000.0,2166000000.0,9856000000.0,7496000000.0,5330000000.0,...,8000000.0,306000000.0,2166000000.0,2166000000.0,1491000000.0,1491000000.0,675000000.0,182000000.0,182000000.0,4221000000.0
2022-12-31,-30894000.0,0.114,9753000000.0,-271000000.0,-271000000.0,6328000000.0,2132000000.0,10455000000.0,9482000000.0,7350000000.0,...,NaN,295000000.0,2132000000.0,2132000000.0,1434000000.0,1434000000.0,698000000.0,271000000.0,271000000.0,6328000000.0
2021-12-31,48900000.0,0.163,8504000000.0,300000000.0,300000000.0,5447000000.0,2062000000.0,9563000000.0,8804000000.0,6742000000.0,...,601000000.0,184000000.0,2062000000.0,2062000000.0,1388000000.0,1388000000.0,674000000.0,-310000000.0,-406000000.0,5447000000.0
2020-12-31,84483000.0,0.189,6098000000.0,447000000.0,447000000.0,3646000000.0,1775000000.0,9809000000.0,6545000000.0,4770000000.0,...,457000000.0,187000000.0,1775000000.0,1775000000.0,1138000000.0,1138000000.0,637000000.0,-429000000.0,-455000000.0,3646000000.0

### Download Fundamentals for Multiple Tickers Using yfinance

In [27]:
tickers = ['FB','AMZN','NFLX','GOOG']
tickers

['FB', 'AMZN', 'NFLX', 'GOOG']

In [28]:
tickers = [yf.Ticker(ticker) for ticker in tickers]
tickers

[yfinance.Ticker object <FB>,
 yfinance.Ticker object <AMZN>,
 yfinance.Ticker object <NFLX>,
 yfinance.Ticker object <GOOG>]

In [29]:
dfs = [] # list for each ticker's dataframe
for ticker in tickers:
    # get each financial statement
    pnl = ticker.financials
    bs = ticker.balancesheet
    cf = ticker.cashflow
    
    # concatenate into one dataframe
    fs = pd.concat([pnl, bs, cf])
    
    # make dataframe format nicer
    data = fs.T # Swap dates and columns
    data = data.reset_index() # reset index (date) into a column
    data.columns = ['Date', *data.columns[1:]] # Rename old index from '' to Date
    data['Ticker'] = ticker.ticker # Add ticker to dataframe
    dfs.append(data)
data

,Date,Tax Effect Of Unusual Items,Tax Rate For Calcs,Normalized EBITDA,Total Unusual Items,Total Unusual Items Excluding Goodwill,Net Income From Continuing Operation Net Minority Interest,Reconciled Depreciation,Reconciled Cost Of Revenue,EBITDA,...,Deferred Income Tax,Depreciation Amortization Depletion,Depreciation And Amortization,Amortization Cash Flow,Amortization Of Intangibles,Depreciation,Operating Gains Losses,Gain Loss On Investment Securities,Net Income From Continuing Operations,Ticker
0,2023-12-31,-286479000.0,0.139,100032000000.0,-2061000000.0,-2061000000.0,73795000000.0,11946000000.0,133332000000.0,97971000000.0,...,-7763000000.0,11946000000.0,11946000000.0,NaN,NaN,11946000000.0,823000000.0,823000000.0,73795000000.0,GOOG
1,2022-12-31,-981507000.0,0.159,91333000000.0,-6173000000.0,-6173000000.0,59972000000.0,13475000000.0,126203000000.0,85160000000.0,...,-8081000000.0,13475000000.0,13475000000.0,641000000.0,641000000.0,13475000000.0,5519000000.0,5519000000.0,59972000000.0,GOOG
2,2021-12-31,1948860000.0,0.162,91491000000.0,12030000000.0,12030000000.0,76033000000.0,12441000000.0,110939000000.0,103521000000.0,...,1808000000.0,12441000000.0,12441000000.0,886000000.0,886000000.0,11555000000.0,-12270000000.0,-12270000000.0,76033000000.0,GOOG
3,2020-12-31,970572126.783412,0.162493,55941000000.0,5973000000.0,5973000000.0,40269000000.0,13697000000.0,84732000000.0,61914000000.0,...,1390000000.0,13697000000.0,13697000000.0,792000000.0,792000000.0,12905000000.0,-6317000000.0,-6317000000.0,40269000000.0,GOOG

In [30]:
data.iloc[:,:3]

        Date Tax Effect Of Unusual Items Tax Rate For Calcs
0 2023-12-31                -286479000.0              0.139
1 2022-12-31                -981507000.0              0.159
2 2021-12-31                1948860000.0              0.162
3 2020-12-31            970572126.783412           0.162493

In [39]:
df = pd.concat(dfs, ignore_index=True)
df = df.set_index(['Ticker','Date'])
df

                  Tax Effect Of Unusual Items Tax Rate For Calcs  \
Ticker Date
AMZN   2023-12-31            211380035.679101           0.189579
       2022-12-31               -3415860000.0               0.21
       2021-12-31           1839997169.143666            0.12558
       2020-12-31            287626230.457441           0.118413
NFLX   2023-12-31                         0.0               0.13
       2022-12-31                         0.0               0.15
       2021-12-31                         0.0               0.12
       2020-12-31                         0.0               0.14
GOOG   2023-12-31                -286479000.0              0.139
       2022-12-31                -981507000.0              0.159
       2021-12-31                1948860000.0              0.162
       2020-12-31            970572126.783412           0.162493

                  Normalized EBITDA Total Unusual Items  \
Ticker Date
AMZN   2023-12-31     88287000000.0        1115000000.0
       2022-12-31     54618000000.0      -16266000000.0
       2021-12-31     59741000000.0       14652000000.0
       2020-12-31     48647000000.0        2429000000.0
NFLX   2023-12-31     21508387000.0                 NaN
       2022-12-31     20332955000.0                 NaN
       2021-12-31     19044502000.0                 NaN
       2020-12-31     15507911000.0                 NaN
GOOG   2023-12-31    100032000000.0       -2061000000.0
       2022-12-31     91333000000.0       -6173000000.0
       2021-12-31     91491000000.0       12030000000.0
       2020-12-31     55941000000.0        5973000000.0

                  Total Unusual Items Excluding Goodwill  \
Ticker Date
AMZN   2023-12-31                           1115000000.0
       2022-12-31                         -16266000000.0
       2021-12-31                          14652000000.0
       2020-12-31                           2429000000.0
NFLX   2023-12-31                                    NaN
       2022-12-31                                    NaN
       2021-12-31                                    NaN
       2020-12-31                                    NaN
GOOG   2023-12-31                          -2061000000.0
       2022-12-31                          -6173000000.0
       2021-12-31                          12030000000.0
       2020-12-31                           5973000000.0

                  Net Income From Continuing Operation Net Minority Interest  \
Ticker Date
AMZN   2023-12-31                                      30425000000.0
       2022-12-31                                      -2722000000.0
       2021-12-31                                      33364000000.0
       2020-12-31                                      21331000000.0
NFLX   2023-12-31                                       5407990000.0
       2022-12-31                                       4491924000.0
       2021-12-31                                       5116228000.0
       2020-12-31                                       2761395000.0
GOOG   2023-12-31                                      73795000000.0
       2022-12-31                                      59972000000.0
       2021-12-31                                      76033000000.0
       2020-12-31                                      40269000000.0

                  Reconciled Depreciation Reconciled Cost Of Revenue  \
Ticker Date
AMZN   2023-12-31           48663000000.0             480980000000.0
       2022-12-31           41921000000.0             446343000000.0
       2021-12-31           34433000000.0             403507000000.0
       2020-12-31           25251000000.0             334564000000.0
NFLX   2023-12-31           14554384000.0              19715368000.0
       2022-12-31           14362814000.0              19168285000.0
       2021-12-31           12438779000.0              17332683000.0
       2020-12-31           10922622000.0              15276319000.0
GOOG   2023-12-31           11946000000.0             133332000000.0
       2022-12-31           13475000000.0             126203000000.0
       2021-12-31           12441000000.0             110939000000.0
       2020-12-31           13697000000.0              84732000000.0

                           EBITDA           EBIT  ... Other Payable  \
Ticker Date                                       ...
AMZN   2023-12-31   89402000000.0  40739000000.0  ...           NaN
       2022-12-31   38352000000.0  -3569000000.0  ...           NaN
       2021-12-31   74393000000.0  39960000000.0  ...           NaN
       2020-12-31   51076000000.0  25825000000.0  ...           NaN
NFLX   2023-12-31   21508387000.0   6954003000.0  ...           NaN
       2022-12-31   20332955000.0   5970141000.0  ...           NaN
       2021-12-31   19044502000.0   6605723000.0  ...           NaN
       2020-12-31   15507911000.0   4585289000.0  ...           NaN
GOOG   2023-12-31   97971000000.0  86025000000.0  ...           NaN
       2022-12-31   85160000000.0  71685000000.0  ...           NaN
       2021-12-31  103521000000.0  91080000000.0  ...   397000000.0
       2020-12-31   61914000000.0  48217000000.0  ...   754000000.0

                  Total Tax Payable Income Tax Payable  \
Ticker Date
AMZN   2023-12-31               NaN                NaN
       2022-12-31               NaN                NaN
       2021-12-31               NaN                NaN
       2020-12-31               NaN                NaN
NFLX   2023-12-31               NaN                NaN
       2022-12-31               NaN                NaN
       2021-12-31               NaN                NaN
       2020-12-31               NaN                NaN
GOOG   2023-12-31      2748000000.0       2748000000.0
       2022-12-31      1632000000.0       1632000000.0
       2021-12-31       808000000.0        808000000.0
       2020-12-31      1485000000.0       1485000000.0

                  Non Current Deferred Assets  \
Ticker Date
AMZN   2023-12-31                         NaN
       2022-12-31                         NaN
       2021-12-31                         NaN
       2020-12-31                         NaN
NFLX   2023-12-31                         NaN
       2022-12-31                         NaN
       2021-12-31                         NaN
       2020-12-31                         NaN
GOOG   2023-12-31               12169000000.0
       2022-12-31                5261000000.0
       2021-12-31                1284000000.0
       2020-12-31                1084000000.0

                  Non Current Deferred Taxes Assets Investments And Advances  \
Ticker Date
AMZN   2023-12-31                               NaN                      NaN
       2022-12-31                               NaN                      NaN
       2021-12-31                               NaN                      NaN
       2020-12-31                               NaN                      NaN
NFLX   2023-12-31                               NaN                      NaN
       2022-12-31                               NaN                      NaN
       2021-12-31                               NaN                      NaN
       2020-12-31                               NaN                      NaN
GOOG   2023-12-31                     12169000000.0            31008000000.0
       2022-12-31                      5261000000.0            30492000000.0
       2021-12-31                      1284000000.0            29549000000.0
       2020-12-31                      1084000000.0            20703000000.0

                  Investmentin Financial Assets Available For Sale Securities  \
Ticker Date
AMZN   2023-12-31                           NaN                           NaN
       2022-12-31                           NaN                           NaN
       2021-12-31                           NaN                           NaN
       2020-12-31                           NaN                           NaN
NFLX   2023-12-31                           NaN                           NaN
       2022-12-31                           NaN                           NaN
       2021-12-31                           NaN                           NaN
       2020-12-31                           NaN                           NaN
GOOG   2023-12-31                 31008000000.0                 31008000000.0
       2022-12-31                 30492000000.0                 30492000000.0
       2021-12-31                 29549000000.0                 29549000000.0
       2020-12-31                 20703000000.0                 20703000000.0

                  Proceeds From Stock Option Exercised  \
Ticker Date
AMZN   2023-12-31                                  NaN
       2022-12-31                                  NaN
       2021-12-31                                  NaN
       2020-12-31                                  NaN
NFLX   2023-12-31                                  NaN
       2022-12-31                                  NaN
       2021-12-31                                  NaN
       2020-12-31                                  NaN
GOOG   2023-12-31                        -9837000000.0
       2022-12-31                        -9300000000.0
       2021-12-31                       -10162000000.0
       2020-12-31                        -5720000000.0

                  Gain Loss On Investment Securities
Ticker Date
AMZN   2023-12-31                                NaN
       2022-12-31                                NaN
       2021-12-31                                NaN
       2020-12-31                                NaN
NFLX   2023-12-31                                NaN
       2022-12-31                                NaN
       2021-12-31                                NaN
       2020-12-31                                NaN
GOOG   2023-12-31                        823000000.0
       2022-12-31                       5519000000.0
       2021-12-31                     -12270000000.0
       2020-12-31                      -6317000000.0

[12 rows x 194 columns]

## Hows to Get Options Data Using yfinance

Options give traders the right but not the obligation to buy or sell underlying assets at a specific price at a predetermined date. Options Trading has matured over the past century and has seen landmark events. Here is a chronicle of the history of options trading and the major events that have led to its evolution.

To download options data, you'll need to use the `Ticker.options` and `Ticker.option_chain` methods.

In [40]:
aapl = yf.Ticker('aapl')
aapl

yfinance.Ticker object <AAPL>

In [41]:
options = aapl.option_chain()

In [42]:
calls = options.calls
calls

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,inTheMoney,contractSize,currency
0,AAPL240315C00005000,2024-03-07 20:50:00+00:00,5.0,164.30,0.00,0.00,0.0,0.0,105,0,0.000010,True,REGULAR,USD
1,AAPL240315C00010000,2024-02-06 14:43:04+00:00,10.0,178.00,158.75,159.45,0.0,0.0,1,0,0.000010,True,REGULAR,USD
2,AAPL240315C00015000,2024-02-14 20:53:09+00:00,15.0,168.80,0.00,0.00,0.0,0.0,9,0,0.000010,True,REGULAR,USD
3,AAPL240315C00020000,2024-02-09 14:30:01+00:00,20.0,168.96,150.35,151.55,0.0,0.0,2,1,0.000010,True,REGULAR,USD
4,AAPL240315C00025000,2024-02-14 20:53:11+00:00,25.0,158.85,0.00,0.00,0.0,0.0,5,0,0.000010,True,REGULAR,USD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68,AAPL240315C00280000,2024-01-22 15:25:10+00:00,280.0,0.01,0.00,0.01,0.0,0.0,4,1029,1.625002,False,REGULAR,USD
69,AAPL240315C00285000,2024-03-11 18:14:39+00:00,285.0,0.01,0.00,0.00,0.0,0.0,6,0,0.500005,False,REGULAR,USD
70,AAPL240315C00290000,2024-02-14 15:07:46+00:00,290.0,0.01,0.00,0.00,0.0,0.0,1,0,0.500005,False,REGULAR,USD
71,AAPL240315C00300000,2024-01-08 14:30:03+00:00,300.0,0.01,0.00,0.00,0.0,0.0,5,3181,0.500005,False,REGULAR,USD
72,AAPL240315C00310000,2024-03-12 18:09:16+00:00,310.0,0.01,0.00,0.00,0.0,0.0,23,0,0.500005,False,REGULAR,USD

In [43]:
type(options)

yfinance.ticker.Options

In [44]:
puts = options.puts
puts

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,inTheMoney,contractSize,currency
0,AAPL240315P00005000,2024-03-12 14:37:18+00:00,5.0,0.01,0.00,0.00,0.0,0.0,3.0,0,0.500005,False,REGULAR,USD
1,AAPL240315P00010000,2024-03-11 13:30:17+00:00,10.0,0.01,0.00,0.00,0.0,0.0,8.0,0,0.500005,False,REGULAR,USD
2,AAPL240315P00050000,2024-03-08 20:01:03+00:00,50.0,0.01,0.00,0.00,0.0,0.0,37.0,0,0.500005,False,REGULAR,USD
3,AAPL240315P00055000,2023-12-12 20:38:56+00:00,55.0,0.01,0.00,0.10,0.0,0.0,3.0,999,4.750004,False,REGULAR,USD
4,AAPL240315P00060000,2024-03-11 16:29:59+00:00,60.0,0.01,0.00,0.00,0.0,0.0,1.0,0,0.500005,False,REGULAR,USD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,AAPL240315P00275000,2022-12-21 17:27:28+00:00,275.0,139.65,137.80,140.10,0.0,0.0,NaN,0,10.095707,True,REGULAR,USD
62,AAPL240315P00280000,2023-05-04 19:09:28+00:00,280.0,114.02,97.05,100.65,0.0,0.0,NaN,0,0.000010,True,REGULAR,USD
63,AAPL240315P00285000,2023-02-15 15:38:45+00:00,285.0,130.86,129.35,131.10,0.0,0.0,3.0,0,7.271974,True,REGULAR,USD
64,AAPL240315P00300000,2023-12-27 18:07:26+00:00,300.0,107.05,106.70,108.20,0.0,0.0,50.0,0,0.000010,True,REGULAR,USD
65,AAPL240315P00310000,2024-01-11 19:10:30+00:00,310.0,124.85,120.80,121.35,0.0,0.0,NaN,0,0.000010,True,REGULAR,USD

## How to Get Institutional Holders Using yfinance

In [45]:
aapl.institutional_holders

,Date Reported,Holder,pctHeld,Shares,Value
0,2023-06-30,Vanguard Group Inc,0.0834,1303688506,252876459508
1,2023-06-30,Blackrock Inc.,0.0665,1039640859,201659137420
2,2023-06-30,"Berkshire Hathaway, Inc",0.0586,915560382,177591247296
3,2023-06-30,State Street Corporation,0.0370,578897858,112288817516
4,2023-06-30,"FMR, LLC",0.0196,307066638,59561715772
5,2023-06-30,"Geode Capital Management, LLC",0.0186,291538165,56549657865
6,2023-06-30,Price (T.Rowe) Associates Inc,0.0145,226650943,43963483413
7,2023-06-30,Morgan Stanley,0.0131,204714950,39708558851
8,2022-12-31,Norges Bank Investment Management,0.0107,167374278,21746939940
9,2023-06-30,Northern Trust Corporation,0.0105,164536073,31915062079

## Why You Shouldn’t Use Yahoo Finance for Live Trading

In [46]:
fb = yf.Ticker('fb')
meta = yf.Ticker('meta')
fb.get_cashflow()

Empty DataFrame
Columns: []
Index: []

In [47]:
meta.get_cashflow()

,2023-12-31,2022-12-31,2021-12-31,2020-12-31
FreeCashFlow,43847000000.0,19044000000.0,38993000000.0,23584000000.0
RepurchaseOfCapitalStock,-19774000000.0,-27956000000.0,-44537000000.0,-6272000000.0
RepaymentOfDebt,-1058000000.0,-850000000.0,-677000000.0,-604000000.0
IssuanceOfDebt,8455000000.0,9921000000.0,0.0,0.0
CapitalExpenditure,-27266000000.0,-31431000000.0,-18690000000.0,-15163000000.0
InterestPaidSupplementalData,448000000.0,0.0,0.0,NaN
IncomeTaxPaidSupplementalData,6607000000.0,6407000000.0,8525000000.0,4229000000.0
EndCashPosition,42827000000.0,15596000000.0,16865000000.0,17954000000.0
BeginningCashPosition,15596000000.0,16865000000.0,17954000000.0,19279000000.0
EffectOfExchangeRateChanges,113000000.0,-638000000.0,-474000000.0,279000000.0
ChangesInCash,27118000000.0,-631000000.0,-615000000.0,-1604000000.0
FinancingCashFlow,-19500000000.0,-22136000000.0,-50728000000.0,-10292000000.0
CashFlowFromContinuingFinancingActivities,-19500000000.0,-22136000000.0,-50728000000.0,-10292000000.0
NetOtherFinancingCharges,-7123000000.0,-3251000000.0,-5514000000.0,-3416000000.0
NetCommonStockIssuance,-19774000000.0,-27956000000.0,-44537000000.0,-6272000000.0
CommonStockPayments,-19774000000.0,-27956000000.0,-44537000000.0,-6272000000.0
NetIssuancePaymentsOfDebt,7397000000.0,9071000000.0,-677000000.0,-604000000.0
NetShortTermDebtIssuance,NaN,NaN,14000000.0,24000000.0
NetLongTermDebtIssuance,7397000000.0,9071000000.0,-677000000.0,-604000000.0
LongTermDebtPayments,-1058000000.0,-850000000.0,-677000000.0,-604000000.0
LongTermDebtIssuance,8455000000.0,9921000000.0,0.0,0.0
InvestingCashFlow,-24495000000.0,-28970000000.0,-7570000000.0,-30059000000.0
CashFlowFromContinuingInvestingActivities,-24495000000.0,-28970000000.0,-7570000000.0,-30059000000.0
NetOtherInvestingChanges,-23000000.0,-4000000.0,-331000000.0,-36000000.0
NetInvestmentPurchaseAndSale,3202000000.0,3532000000.0,12179000000.0,-14520000000.0
SaleOfInvestment,6184000000.0,13158000000.0,42586000000.0,25771000000.0
PurchaseOfInvestment,-2982000000.0,-9626000000.0,-30407000000.0,-40291000000.0
NetBusinessPurchaseAndSale,-629000000.0,-1312000000.0,-851000000.0,-388000000.0
PurchaseOfBusiness,-629000000.0,-1312000000.0,-851000000.0,-388000000.0
NetPPEPurchaseAndSale,-27045000000.0,-31186000000.0,-18567000000.0,-15115000000.0
SaleOfPPE,221000000.0,245000000.0,123000000.0,48000000.0
PurchaseOfPPE,-27266000000.0,-31431000000.0,-18690000000.0,-15163000000.0
OperatingCashFlow,71113000000.0,50475000000.0,57683000000.0,38747000000.0
CashFlowFromContinuingOperatingActivities,71113000000.0,50475000000.0,57683000000.0,38747000000.0
ChangeInWorkingCapital,3836000000.0,5683000000.0,700000000.0,-2723000000.0
ChangeInOtherWorkingCapital,NaN,NaN,187000000.0,108000000.0
ChangeInOtherCurrentLiabilities,624000000.0,886000000.0,941000000.0,-527000000.0
ChangeInOtherCurrentAssets,-80000000.0,-106000000.0,-349000000.0,-34000000.0
ChangeInPayablesAndAccruedExpense,5132000000.0,4510000000.0,4968000000.0,-785000000.0
ChangeInAccruedExpense,5352000000.0,4210000000.0,3544000000.0,-946000000.0
ChangeInPayable,-220000000.0,300000000.0,1424000000.0,161000000.0
ChangeInAccountPayable,51000000.0,210000000.0,1436000000.0,-17000000.0
ChangeInPrepaidAssets,559000000.0,162000000.0,-1750000000.0,135000000.0
ChangeInReceivables,-2399000000.0,231000000.0,-3110000000.0,-1512000000.0
ChangesInAccountReceivables,-2399000000.0,231000000.0,-3110000000.0,-1512000000.0
OtherNonCashItems,411000000.0,1982000000.0,-127000000.0,85000000.0
StockBasedCompensation,14027000000.0,11992000000.0,9164000000.0,6536000000.0
UnrealizedGainLossOnInvestmentSecurities,NaN,463000000.0,-232000000.0,33000000.0
AssetImpairmentCharge,2432000000.0,2218000000.0,0.0,0.0
DeferredTax,131000000.0,-3286000000.0,609000000.0,-1192000000.0
DeferredIncomeTax,131000000.0,-3286000000.0,609000000.0,-1192000000.0
DepreciationAmortizationDepletion,11178000000.0,8686000000.0,7967000000.0,6862000000.0
DepreciationAndAmortization,11178000000.0,8686000000.0,7967000000.0,6862000000.0
NetIncomeFromContinuingOperations,39098000000.0,23200000000.0,39370000000.0,29146000000.0